# **Q0.Import libraries.**

In [ ]:
import pandas as pd

# **Q1.Load the CSV using Pandas.**
df=pd.read_csv("/content/Practice.csv")

In [ ]:
df=pd.read_csv("/content/Practice.csv")

# **Q2.How many rows and columns are there?**
15 rows and 8 columns

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  15 non-null     int64
 1   Date      15 non-null     object
 2   Product   15 non-null     object
 3   Category  15 non-null     object
 4   City      15 non-null     object
 5   Quantity  15 non-null     int64
 6   Price     15 non-null     int64
 7   Rating    15 non-null     float64
 8   Payment   15 non-null     object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.2+ KB

# **Q3.What are the column names?**
'Order_ID',
 'Date',
 'Product',
 'Category',
 'City',
 'Quantity',
 'Price',
 'Rating',
 'Payment'

In [ ]:
list(df.columns)

['Order_ID',
 'Date',
 'Product',
 'Category',
 'City',
 'Quantity',
 'Price',
 'Rating',
 'Payment']

# **Q4.Are there any missing values?**
no

In [ ]:
df.isnull().sum()

Order_ID    0
Date        0
Product     0
Category    0
City        0
Quantity    0
Price       0
Rating      0
Payment     0
dtype: int64

# **Q5.What is the average product rating?**
4.24

In [ ]:
df["Rating"].mean()

np.float64(4.24)

# **Q6.What is the total quantity of products sold?**
25

In [ ]:
df["Quantity"].sum()

np.int64(25)

# **Q7.What is the average order value?**
13,110

In [ ]:
df["Price"].mean()

np.float64(13110.0)

# **Q8.Create a new column called 'Sales'.**
df["Sales"]=df["Quantity"]*df["Price"]

In [ ]:
df["Sales"]=df["Quantity"]*df["Price"]

# **Q9.What is the total revenue?**
210,900

In [ ]:
total_revenue=df["Sales"].sum()
total_revenue

np.int64(210900)

# **Q10.Which product generated the highest revenue?**
Laptop	173,000

In [ ]:
df.groupby("Product")["Sales"].sum()

Product
Headphones      7800
Keyboard        5200
Laptop        173000
Mouse           3900
Shoes          12700
T-Shirt         8300
Name: Sales, dtype: int64

# **Q11.Which city generated the highest revenue?**
Pune	71,100

In [ ]:
df.groupby("City")["Sales"].sum()

City
Delhi     69100
Mumbai    70700
Pune      71100
Name: Sales, dtype: int64

# **Q12.What is the total revenue from Electronics?**
Electronics	189,900

In [ ]:
df.groupby("Category")["Sales"].sum()

Category
Electronics    189900
Fashion         21000
Name: Sales, dtype: int64

# **Q13.What is the total revenue from Fashion?**
Fashion	21,000

In [ ]:
df.groupby("Category")["Sales"].sum()

Category
Electronics    189900
Fashion         21000
Name: Sales, dtype: int64

# **Q14.Which payment method was used most frequently?**
UPI	6

In [ ]:
df.groupby("Payment")["Payment"].count()

Payment
Card    5
Cash    4
UPI     6
Name: Payment, dtype: int64

# **Q15.What is the average quantity per order?**
1.7

In [ ]:
round(df["Quantity"].mean(),1)

np.float64(1.7)